---
# dkms molecule/default/verify.yml
#
# SPDX-FileCopyrightText: © 2021 Open Networking Foundation <support@opennetworking.org>
# SPDX-License-Identifier: Apache-2.0

- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include dkms"
      include_role:
        name: "dkms"
